### ISSUE TITLE
javascript jquery and json

### ISSUE THREAD

**Issue by Pawan-dabi** [jaredbest/javascript-jquery-and-json#1]
hii there, 
this is pawan and i am facing some problem related to javascript jquery and json of week 1 assignment.
i am able to login in of this assignment.
so please help me

**Comment by jaredbest** [comment]
Hi @Pawan-dabi, what do you mean by "I am able to login"? Do you mean "unable"? I need some context to what specifically you are referring to.

**Comment by Pawan-dabi** [comment]
Hi, when i am login on the webpage, again i am coming back back on the same page. I am unable to rich on add.php file(webpage) where i have to add some entry on the server.
This is the problem i am facing.
![before login](https://user-images.githubusercontent.com/72254804/126855709-ca6afd62-fb33-4e45-b9f1-0eee4921eb6f.PNG)
![after login](https://user-images.githubusercontent.com/72254804/126855711-0a2070ad-bfac-4c2c-b5f2-362a888da79c.PNG)

**Comment by Pawan-dabi** [comment]
Here you can see it, again i am on the same page after login.
Don't know what's going wrong with me.

What i supposed to do right now, can you solve this problem ?

**Comment by Pawan-dabi** [comment]
Hi, when i am login on the webpage, again i am coming back back on the same page. I am unable to rich on add.php file(webpage) where i have to add some entry on the server.
This is the problem i am facing.

here is before login.
![beforelogin](https://user-images.githubusercontent.com/72254804/126856074-8c7db78d-fd81-42a0-bb8a-b9997873705e.PNG)

and here is after login.
![afterlogin](https://user-images.githubusercontent.com/72254804/126856088-19c02359-f25c-4c9e-9eea-2a6bec57b299.PNG)

**Comment by Pawan-dabi** [comment]
Here you can see it, again i am on the same page after login.
Don't know what's going wrong with me.

What i supposed to do right now, can you solve this problem ?
